name: '"Configure Alibaba Cloud Credentials" Action for GitHub Actions'
description: 'Configures Alibaba Cloud credentials for use in subsequent steps in a GitHub Action workflow'
inputs:
  oidc-provider-arn:
    description: 'The ARN of OIDC provider. format: acs:ram::USER_Id:oidc-provider/ROLE_NAME'
    required: false
  role-to-assume:
    description: 'Required for OIDC user. The ARN of role to assume. format: acs:ram::USER_Id:role/ROLE_NAME'
    required: false
  role-session-expiration:
    description: "Role roleSessionExpiration in seconds (default: 1800 seconds)"
    required: false
    default: 1800
  role-session-name:
    description: 'Role session name'
    required: false
    default: 'github-action-session'
  audience:
    description: 'The audience to use for the OIDC provider'
    required: false
    default: 'sts.aliyuncs.com'
  role-chaining:
    description: 'Whether to use role chaining. Use existing credentials to assume another role'
    required: false

outputs:
  aliyun-access-key-id:
    description: The alibaba cloud access key ID for the provided credentials
  aliyun-access-key-secret:
    description: The alibaba cloud access key secret for the provided credentials
  aliyun-security-token:
    description: The alibaba cloud security token for the provided credentials

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'

branding:
  color: orange
  icon: cloud