name: '"Configure Alibaba Cloud Credentials" Action for GitHub Actions'
description: 'Configures Alibaba Cloud credentials for use in subsequent steps in a GitHub Action workflow'
inputs:
  oidc-provider-arn:
    description: 'The ARN of OIDC provider. format: acs:ram::USER_Id:oidc-provider/ROLE_NAME'
    required: false
  role-to-assume:
    description: 'The ARN of role to assume. format: acs:ram::USER_Id:role/ROLE_NAME'
    required: false

outputs:
  aliyun-access-key-id:
    description: The alibaba cloud access key ID for the provided credentials
  aliyun-access-key-secret:
    description: The alibaba cloud access key secret for the provided credentials
  aliyun-security-token:
    description: The alibaba cloud security token for the provided credentials
runs:
  using: 'node16'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'

branding:
  color: orange
  icon: cloud